services:
  your-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: oversyn-img
    container_name: oversyn-cont
    volumes:
      - ./:/app
    ports:
      - '5173:5173'
    # working_dir: /app
    command: npm run dev -- --host 0.0.0.0
