[package]
name = "generator"
version = "0.7.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.11"
ic-cdk-macros = "0.8.0"
ic-cdk = "0.11.3"
ic-stable-structures = "0.6.0"
ic-ledger-types = "0.8.0"
serde = "1.0.190"
